In [5]:
import numpy as np

# 1. Одновимірний масив (вектор) з першими 10-ма натуральними числами

vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# 2. Двовимірний масив (матриця) розміром 3x3, заповнений нулями

matrix_zeros = np.zeros((3, 3))
print(matrix_zeros)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:

# 3. Масив розміром 5x5, заповнений випадковими цілими числами в діапазоні від 1 до 10

matrix_random_int = np.random.randint(1, 11, (5, 5))
print(matrix_random_int)



[[ 9  9  2  9  9]
 [ 3  7  5 10  5]
 [ 2  6  3 10  1]
 [ 8  2  9  6  5]
 [ 9  4  9  8  8]]


In [8]:
# 4. Масив розміром 4x4, заповнений випадковими дійсними числами в діапазоні від 0 до 1

matrix_random_float = np.random.random((4, 4))
print(matrix_random_float)

[[0.84137797 0.80596788 0.83440617 0.50471241]
 [0.72147687 0.86424471 0.34109263 0.96587472]
 [0.14264533 0.48673134 0.81130919 0.51864144]
 [0.37233113 0.17440982 0.69698093 0.6838478 ]]


In [9]:
# 5. Поелементні операції додавання, віднімання та множення для двох одновимірних масивів

array1 = np.random.randint(1, 11, 5)
array2 = np.random.randint(1, 11, 5)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)

Addition: [12 12 13 16 12]
Subtraction: [-8  2  5 -4  8]
Multiplication: [20 35 36 60 20]


In [10]:
# 6. Скалярний добуток двох векторів розміром 7

vector1 = np.random.random(7)
vector2 = np.random.random(7)

dot_product = np.dot(vector1, vector2)
print("Scalar product:", dot_product)

Scalar product: 3.005259221141884


In [11]:
# 7. Перемноження двох матриць 2x2 та 2x3

matrix1 = np.random.randint(1, 11, (2, 2))
matrix2 = np.random.randint(1, 11, (2, 3))

product = np.dot(matrix1, matrix2)
print(product)

[[111 125  44]
 [ 39  53  20]]


In [12]:
# 8. Обернена матриця 3x3

matrix3x3 = np.random.randint(1, 11, (3, 3))
inverse_matrix = np.linalg.inv(matrix3x3)
print(inverse_matrix)

[[ 0.1875      0.08333333 -0.14583333]
 [-0.0625      0.25       -0.0625    ]
 [-0.09375    -0.20833333  0.23958333]]


In [13]:
# 9. Транспонування матриці 4x4

matrix4x4 = np.random.random((4, 4))
transposed_matrix = matrix4x4.T
print(transposed_matrix)

[[0.83877017 0.84275505 0.81170807 0.62518617]
 [0.44890574 0.43296428 0.81599495 0.42668133]
 [0.79226522 0.26321981 0.71339683 0.50350532]
 [0.2053418  0.09387887 0.74769128 0.62191866]]


In [14]:
# 9.                Транспонування матриці 4x4

matrix4x4 = np.random.random((4, 4))
transposed_matrix = matrix4x4.T
print(transposed_matrix)

[[0.32446456 0.59594109 0.86196299 0.74385749]
 [0.43581392 0.9875999  0.25872199 0.59017507]
 [0.21397859 0.10721945 0.34130706 0.89738991]
 [0.04127015 0.30077277 0.64239948 0.06374517]]


In [15]:
# 10. Перемноження матриці 3x4 та вектора 4

matrix3x4 = np.random.randint(1, 11, (3, 4))
vector4 = np.random.randint(1, 11, 4)

product_mv = np.dot(matrix3x4, vector4)
print(product_mv)

[ 96  91 163]


In [16]:
# 11. Перемноження матриці 2x3 та вектора 3

matrix2x3 = np.random.random((2, 3))
vector3 = np.random.random(3)

product_mv = np.dot(matrix2x3, vector3)
print(product_mv)

[0.25180109 0.2118465 ]


In [17]:
# 12. Поелементне множення двох матриць 2x2

matrix_a = np.random.randint(1, 11, (2, 2))
matrix_b = np.random.randint(1, 11, (2, 2))

elementwise_multiplication = matrix_a * matrix_b
print(elementwise_multiplication)

[[16 42]
 [20 10]]


In [18]:
# 13. Добуток двох матриць 2x2

matrix_a = np.random.randint(1, 11, (2, 2))
matrix_b = np.random.randint(1, 11, (2, 2))

matrix_product = np.dot(matrix_a, matrix_b)
print(matrix_product)

[[79 95]
 [63 83]]


In [19]:
# 14. Сума елементів матриці 5x5

matrix5x5 = np.random.randint(1, 101, (5, 5))
matrix_sum = np.sum(matrix5x5)
print(matrix_sum)

1426


In [20]:
# 15. Різниця двох матриць 4x4

matrix_a = np.random.randint(1, 11, (4, 4))
matrix_b = np.random.randint(1, 11, (4, 4))

matrix_difference = matrix_a - matrix_b
print(matrix_difference)

[[-3  2  0  4]
 [-3  8  2  2]
 [-8 -3  1  0]
 [-7 -8  5 -1]]


In [21]:
# 16. Вектор-стовпчик з сумою елементів кожного рядка матриці 3x3

matrix3x3 = np.random.random((3, 3))
row_sums = np.sum(matrix3x3, axis=1).reshape(-1, 1)
print(row_sums)

[[1.74252542]
 [1.25496551]
 [1.71965391]]


In [22]:
# 17. Матриця з квадратами елементів іншої матриці

matrix3x4 = np.random.randint(1, 11, (3, 4))
squared_matrix = np.square(matrix3x4)
print(squared_matrix)

[[100 100  64  25]
 [100   4  81  49]
 [ 64  25 100  36]]


In [23]:
# 18. Вектор з квадратними коренями чисел

vector4 = np.random.randint(1, 51, 4)
sqrt_vector = np.sqrt(vector4)
print(sqrt_vector)

[4.35889894 4.58257569 5.47722558 1.41421356]
